# Generated by Django 5.2.9 on 2026-01-23 18:45

import Perfil.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionperfil', models.CharField(max_length=50)),
                ('perfilactivo', models.IntegerField(default=1)),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacimiento', models.DateField(validators=[Perfil.models.validar_no_futuro])),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
            ],
            options={
                'verbose_name': 'Datos Personales',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField(validators=[Perfil.models.validar_no_futuro])),
                ('fechafin', models.DateField(validators=[Perfil.models.validar_no_futuro])),
                ('totalhoras', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcioncurso', models.CharField(blank=True, max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados_cursos/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargodesempenado', models.CharField(max_length=100)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('emailempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField(validators=[Perfil.models.validar_no_futuro])),
                ('fechafingestion', models.DateField(blank=True, null=True, validators=[Perfil.models.validar_no_futuro])),
                ('descripcionfunciones', models.CharField(max_length=100)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados_laborales/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField(validators=[Perfil.models.validar_no_futuro])),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiporeconocimiento', models.CharField(max_length=100)),
                ('fechareconocimiento', models.DateField(validators=[Perfil.models.validar_no_futuro])),
                ('descripcionreconocimiento', models.CharField(max_length=100)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, upload_to='certificados_reconocimientos/')),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='Perfil.datospersonales')),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], default='Bueno', max_length=40)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_garage/')),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('idperfilconqueestaactivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_garage', to='Perfil.datospersonales')),
            ],
        ),
    ]
